#!/usr/bin/env python3
"""
Update existing MobiWork form with Edenwald Senior Living data.
The script fills the SalesReportingForm with the latest ETL outputs.
"""
import math
import os
import re
import sys
import xml.etree.ElementTree as ET
from decimal import Decimal, InvalidOperation, ROUND_HALF_UP
from pathlib import Path
from xml.sax.saxutils import escape

import pandas as pd
import requests
import yaml

# MobiWork API Configuration
def require_env(name, description):
    value = os.getenv(name)
    if not value:
        print(f"✗ Missing environment variable {name} ({description}).", file=sys.stderr)
        print("  Create a .env file (see .env.example) or export the variable before running.", file=sys.stderr)
        sys.exit(1)
    return value


API_LOGIN_ID = require_env("MOBI_API_LOGIN_ID", "MobiWork API login ID")
API_PASSWORD = require_env("MOBI_API_PASSWORD", "MobiWork API password")
CLIENT_ID = require_env("MOBI_CLIENT_ID", "MobiWork client ID")
API_VERSION = os.getenv("MOBI_API_VERSION", "10.4.109")
FORM_ID = os.getenv("MOBI_FORM_ID", "165008")  # SalesReportingForm template ID
FILLED_FORM_ID = os.getenv("MOBI_FILLED_FORM_ID", "145683277")  # Existing filled form instance
MOBI_BASE_URL = os.getenv("MOBI_BASE_URL", "https://platform.mobiwork.com").rstrip("/")

TARGET_CUSTOMER_ID = float(os.getenv("MOBI_TARGET_CUSTOMER_ID", "10812"))  # Edenwald Senior Living external ID
CONFIG_PATH = Path("config/config.yaml")


def norm(value):
    return re.sub(r"[^A-Z0-9]+", " ", str(value).strip().upper()).strip()


def load_cfg(path: Path):
    if path.exists():
        with open(path, "r", encoding="utf-8") as fh:
            return yaml.safe_load(fh) or {}
    return {}


def build_variant_lookup(cfg):
    groups = cfg.get("sku_variant_groups") or {}
    lookup = {}
    for group_name, variants in groups.items():
        group_key = norm(group_name)
        lookup[group_key] = group_key
        if isinstance(variants, list):
            for variant in variants:
                lookup[norm(variant)] = group_key
    return lookup


def main():
    cfg = load_cfg(CONFIG_PATH)
    sku_group_lookup = build_variant_lookup(cfg)

    # Read data generated by the ETL
    try:
        parent = pd.read_csv("out/parent_snapshot.csv")
        top_skus = pd.read_csv("out/top_skus_lines.csv")
    except FileNotFoundError as exc:
        print(f"✗ Missing ETL output: {exc}")
        print("  Run etl_salesreport_detail.py first.")
        sys.exit(1)

    # Fetch Edenwald data
    try:
        edenwald_parent = parent[parent["Customer"] == TARGET_CUSTOMER_ID].iloc[0]
    except IndexError:
        print("✗ Edenwald Senior Living not found in parent_snapshot.csv.")
        print("  Ensure customer mapping is complete and ETL outputs are up to date.")
        sys.exit(1)

    edenwald_skus = top_skus[top_skus["Customer"] == TARGET_CUSTOMER_ID].reset_index(drop=True)
    mp_sku = edenwald_parent["Most Popular SKU"]

    def fmt_qty(val):
        if pd.isna(val):
            return ""
        if isinstance(val, str):
            return val
        if math.isclose(val, round(val)):
            return str(int(round(val)))
        return f"{val:.2f}".rstrip("0").rstrip(".")

    # Summary metrics
    def fmt_int(value):
        if value is None:
            return ""
        if isinstance(value, str):
            value = value.strip()
            if not value:
                return ""
        try:
            if pd.isna(value):
                return ""
        except TypeError:
            pass
        try:
            dec = Decimal(str(value))
            dec = dec.quantize(Decimal("1"), rounding=ROUND_HALF_UP)
            return str(int(dec))
        except (InvalidOperation, ValueError):
            return str(value)

    summary_last_month = fmt_int(edenwald_parent.get("Last Month Qty"))
    summary_avg_value = None

    mp_group_key = sku_group_lookup.get(norm(mp_sku), norm(mp_sku))
    if not edenwald_skus.empty:
        grouped = edenwald_skus.copy()
        grouped["sku_group_key"] = grouped["SKU"].map(lambda s: sku_group_lookup.get(norm(s), norm(s)))
        group_rows = grouped[grouped["sku_group_key"] == mp_group_key]
        if not group_rows.empty:
            if "6M Avg Qty" in group_rows:
                summary_avg_value = float(group_rows["6M Avg Qty"].sum())
            elif "3M Avg Qty" in group_rows:
                summary_avg_value = float(group_rows["3M Avg Qty"].sum())

    if summary_avg_value is None:
        parent_avg = edenwald_parent.get("6-Month Avg")
        if parent_avg is not None and not pd.isna(parent_avg):
            summary_avg_value = float(parent_avg)
    if summary_avg_value is None and "6M Avg Qty" in edenwald_skus:
        summary_avg_value = float(edenwald_skus["6M Avg Qty"].sum())
    if summary_avg_value is None and "3M Avg Qty" in edenwald_skus:
        summary_avg_value = float(edenwald_skus["3M Avg Qty"].sum())

    summary_avg_month = fmt_int(summary_avg_value)

    print("=" * 80)
    print("UPDATE MOBIWORK FORM - EDENWALD SENIOR LIVING")
    print("=" * 80)
    print("\nData to update:")
    print(f"  Customer: {int(edenwald_parent['Customer'])}")
    print(f"  Agreement Level: {edenwald_parent['Agreement Level']}")
    print(f"  Visit Frequency: {edenwald_parent['Visit Frequency']}")
    print(f"  Most Popular SKU: {edenwald_parent['Most Popular SKU']}")
    print(f"  Last Month Qty: {summary_last_month}")
    avg_label = "Avg Monthly Qty (6M window)"
    if mp_group_key != norm(mp_sku):
        avg_label += f" ({mp_group_key} variants)"
    print(f"  {avg_label}: {summary_avg_month or 'unavailable'}")
    print(f"  Report Period: {edenwald_parent['ReportPeriod']}")

    # Step 1: Authenticate
    print("\n1. AUTHENTICATING...")
    auth_url = f"{MOBI_BASE_URL}/api/rest/{CLIENT_ID}/{API_VERSION}/authenticate.html"
    auth_data = f"""<request>
  <apiLoginId>{API_LOGIN_ID}</apiLoginId>
  <apiPassword>{API_PASSWORD}</apiPassword>
</request>"""

    headers = {"Content-Type": "application/xml"}

    try:
        auth_response = requests.post(auth_url, data=auth_data, headers=headers, timeout=10)
    except Exception as exc:
        print(f"   ✗ Authentication error: {exc}")
        sys.exit(1)

    if auth_response.status_code != 200:
        print(f"   ✗ Authentication failed: {auth_response.status_code}")
        sys.exit(1)

    root = ET.fromstring(auth_response.text)
    token = root.findtext("token")
    if not token:
        print("   ✗ Authentication failed: token not found in response")
        sys.exit(1)

    print("   ✓ Authentication successful!")
    print(f"   Token: {token}")

    # Step 2: Update the existing form
    print(f"\n2. UPDATING FILLED FORM ID: {FILLED_FORM_ID}...")

    fields_xml = []

    field_meta = {
        "Customer": (1, "Customer"),
        "AgreementLevel": (6, "Agreement Level"),
        "VisitFrequency": (1, "Visit Frequency"),
        "MostPopularSKU": (1, "Most Popular SKU"),
        "LastMonthQty": (2, "Last Month Qty"),
        "MonthTotal": (2, "Avg monthly"),
        "SKU": (1, "SKU"),
        "ItemName": (1, "Item Name"),
        "LastMonthQty1": (2, "Last Month Qty"),
        "LastMonthQty2": (2, "Last Month Qty"),
        "ExpectedQtyPerMonth": (2, "Expected Qty Per Month"),
    }

    def add_field(api_name, value, index=0):
        if value is None:
            return
        value_str = str(value).strip()
        if value_str == "":
            return
        field_type, label = field_meta.get(api_name, (1, api_name))
        fields_xml.append(
            f"""    <formField>
      <fieldType>{field_type}</fieldType>
      <apiName>{api_name}</apiName>
      <index>{index}</index>
      <name>{escape(label)}</name>
      <value>{escape(value_str)}</value>
    </formField>"""
        )

    add_field("Customer", int(edenwald_parent["Customer"]))
    add_field("AgreementLevel", edenwald_parent["Agreement Level"])
    add_field("VisitFrequency", edenwald_parent.get("Visit Frequency"))
    add_field("MostPopularSKU", mp_sku)
    add_field("LastMonthQty", summary_last_month)
    add_field("MonthTotal", summary_avg_month)

    for idx, row in edenwald_skus.head(10).iterrows():
        add_field("SKU", row["SKU"], idx)
        add_field("ItemName", row.get("Item Name", ""), idx)
        add_field("LastMonthQty1", fmt_qty(row.get("Last Month Qty")), idx)
        add_field("LastMonthQty2", fmt_qty(row.get("3M Avg Qty")), idx)
        if "Expected Qty/Month" in row.index:
            exp_val = fmt_qty(row.get("Expected Qty/Month"))
            if exp_val:
                add_field("ExpectedQtyPerMonth", exp_val, idx)

    fields_block = "\n".join(fields_xml)

    form_xml = f"""<mobiForm>
  <filledFormId>{FILLED_FORM_ID}</filledFormId>
  <name>SalesReportingForm</name>
  <apiName>SalesReportingForm</apiName>
  <status>PROCESSED</status>
  <formFields>
{fields_block}
  </formFields>
</mobiForm>"""

    update_url = (
        f"{MOBI_BASE_URL}/api/rest/{CLIENT_ID}/{API_VERSION}/mobiForm/{FILLED_FORM_ID}/update.html?token={token}"
    )
    print(f"   Endpoint: /api/rest/{CLIENT_ID}/{API_VERSION}/mobiForm/{FILLED_FORM_ID}/update.html")

    try:
        response = requests.post(update_url, data=form_xml, headers=headers, timeout=10)
    except Exception as exc:
        print(f"   ✗ Error sending form update: {exc}")
        sys.exit(1)

    print(f"   Status: {response.status_code}")
    print("\n   Response:")
    print(f"   {response.text}")

    if response.status_code != 200:
        print("   ✗ Form update failed due to HTTP error.")
        sys.exit(1)

    resp_root = ET.fromstring(response.text)
    status_code = resp_root.get("statusCode")

    if status_code == "1":
        print("\n   ✓✓✓ SUCCESS! Form updated in MobiWork!")
        print("\n   Updated fields:")
        print(f"     - Agreement Level: {edenwald_parent['Agreement Level']}")
        print(f"     - Visit Frequency: {edenwald_parent['Visit Frequency']}")
        print(f"     - Most Popular SKU: {edenwald_parent['Most Popular SKU']}")
        print(f"     - Last Month Qty: {summary_last_month}")
        print(f"     - Avg Monthly Qty: {summary_avg_month}")
    else:
        error = resp_root.find(".//error")
        if error is not None:
            print(f"\n   ✗ Error: {error.text}")
            print(f"   Error code: {error.get('code')}")
        sys.exit(1)

    print("\n" + "=" * 80)


if __name__ == "__main__":
    main()
